### ISSUE TITLE
Doesn't work on Xamarin Studio

### ISSUE THREAD

**Issue by makerofthings7** [Redth/AndroidSignatureToolAddin#1]
I get this error when using Xamarin studio's plugins. 

<img width="824" alt="screen shot 2017-04-21 at 12 17 16 pm" src="https://cloud.githubusercontent.com/assets/606120/25286769/e3b4e450-268c-11e7-9f91-a29ec17b9a88.png">

**Comment by Redth** [comment]
Please move to Visual Studio for Mac :)
